version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      network: host
    ports:
      - '8080:8080'
    links:
      - database
    environment:
      DB_URI: 'mongodb://database:27017/alias'

  database:
    image: mongo:5.0.1
    command: mongod --quiet
    ports:
      - '27017:27017'
